### ISSUE TITLE
ProtRank help

### ISSUE THREAD

**Issue by josenimo** [8medom/ProtRank#2]
Dear @8medom ,

I am trying our ProtRank for my label-free proteomic readout. 
In my dataset I have 6 samples, 3 controls, and 3 biologically perturbed. I am hoping to compare 3v3. I unfortunately cannot understand the code that well, and the documentation seems rather poor.

Could you help me?

What would the `what_to_compare` argument would look like? 
right now it is: `what_to_compare = [[[18, 33], [167,82], [187,108]]]`
Samples 18,167,187 belong to the control group.
Samples 33, 82, 108 belong to the experimental group.
Other questions:
Could I not simply have a caterogical A or B, and compare all samples with these labels?
These samples are not paired, is it possible to run unpaired comparisons?

thank you for this great tool,
Best,
Jose

**Comment by 8medom** [comment]
Dear Jose,


Sorry to hear that you have trouble with using the package! You are right about what_to_compare - it contains the names of the columns that are to be compared. Those names are normally strings, so maybe it may be necessary to change your code to

what_to_compare = [[['18', '33'], ['167','82'], ['187','108']]] (btw, those column names look dangerously cryptic). But you can also make sure that your column names are integers and then that would not be necessary.


Could I not simply have a caterogical A or B, and compare all samples with these labels?

That's a nice idea for the future! It could make life somewhat easier for large datasets where one would otherwise have to programmatically specify the columns that are to be compared. I will think about it.


These samples are not paired, is it possible to run unpaired comparisons?

The algorithm works in a paired manner. If you want, you can run it multiple times with different pairings to see how sensitive are the results (then either choose a representative outcome or, if the results are more substantial, aggregate the results by averaging or intersection).

I hope this is somewhat helpful. Let me know if you have other questions. Have a nice summer!

Best wishes,
matus



________________________________
From: Jose Nimo ***@***.***>
Sent: Wednesday, August 2, 2023 2:25 PM
To: 8medom/ProtRank
Cc: MEDO Matus; Mention
Subject: [8medom/ProtRank] ProtRank help (Issue #2)

Dear @8medom , I am trying our ProtRank for my label-free proteomic readout. In my dataset I have 6 samples, 3 controls, and 3 biologically perturbed. I am hoping to compare 3v3. I unfortunately cannot understand the code that well, and the


Dear @8medom<https://urldefense.com/v3/__https://github.com/8medom__;!!Dc8iu7o!zS3JK8w8v7sdoKR9kBQJPBmfbwAyQOwQAdWMy2ORpiDJwhq7nRYVSYt_LK4fv_pN-cYoWFDU8rZgyO6IaV1VU7e4eo8$> ,

I am trying our ProtRank for my label-free proteomic readout.
In my dataset I have 6 samples, 3 controls, and 3 biologically perturbed. I am hoping to compare 3v3. I unfortunately cannot understand the code that well, and the documentation seems rather poor.

Could you help me?

What would the what_to_compare argument would look like?
right now it is: what_to_compare = [[[18, 33], [167,82], [187,108]]]
Samples 18,167,187 belong to the control group.
Samples 33, 82, 108 belong to the experimental group.
Other questions:
Could I not simply have a caterogical A or B, and compare all samples with these labels?
These samples are not paired, is it possible to run unpaired comparisons?

thank you for this great tool,
Best,
Jose

**Comment by josenimo** [comment]
Dear matus, 
thank you for your quick response,
my column headers are integers, and they are cryptic by design since they are patient ids (: 
I think it would be a very great addition to the current proteomic analytical tools, especially in python. I have met with many proteomic experts and they all consider it a great idea, usually much better than imputing, just hard to implement.
I understand, unfortunately, the current state of ProtRank is not implementable by myself, I have many samples for each group, and running these permutations is not feasable.
Have a nice summer,
Best,
Jose

**Comment by 8medom** [comment]
Dear Jose,
Having many samples for each group sounds very interesting - I haven't come across such a case in proteomics yet. I'm that one could work out something... If you are interested, we could take a closer look together, let me know.

Best,
m
